earist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hris.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hris/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import *



urlpatterns = [
        path('register/', views.registerPage, name='register'),
        path('login/', views.loginPage, name='login'),
        path('logout/', views.logoutUser, name='logout'),
        path("", views.home, name="home"),
        path('account/', views.accountSettings, name="account"),
        path('user/', views.userPage, name='user-page'),
        path('upload/', views.upload_file, name='upload_file'),
        path('upload/success/', views.upload_success, name='upload_success'),  # Add this line
        path('search/', views.search_records, name='search_records'),
        path('dtr/', views.search_attendance, name='search_attendance'),
        path('search_attendance/', views.search_attendance_record, name='search_attendance_record'),
        path('edit/<int:record_id>/', views.edit_attendance_record, name='edit_attendance_record'),
        path('attendance_records/', views.view_attendance_records, name='attendance_records'),
        path('official_time/', views.official_time_view, name='official_time'),
        path('edit-logs/', views.edit_logs, name='edit_logs'),
        path('pds1/', views.pds1, name='pds1'),
        path('pds2/', views.pds2, name='pds2'),
        path('pds3/', views.pds3, name='pds3'),
        path('pds4/', views.pds4, name='pds4'),

]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  

        # # path("products/", views.products, name='products'),
        # path("profile/<str:pk_test>/", views.customer, name='customer'),
        # path('create_order/<str:pk>/', views.createOrder, name='create_order'),
        # path('update_order/<str:pk>/', views.updateOrder, name='update_order'),
        # path('delete_order/<str:pk>/', views.deleteOrder, name='delete_order'),
        # path('reset_password', auth_views.PasswordResetView.as_view(), name='reset_password'),
        # path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
        # path('reset/<uidb64>/<toke>/', auth_views.PasswordResetConfirmView.as_view(), name='passqord_reset_confirm'),
        # path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

hris/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import *
from django import forms
from django.forms import modelformset_factory
from .models import AttendanceRecord
from django.forms import BaseFormSet
from django.forms import BaseModelFormSet
from django.forms.renderers import get_default_renderer

class ReadOnlyField(forms.CharField):
    widget = forms.TextInput(attrs={'readonly': 'readonly'})

    def clean(self, value):
        return value

class OfficialTimeForm(forms.ModelForm):
    class Meta:
        model = OfficialTime
        fields = ['day','official_office_in', 'official_office_out', 'official_honorarium_time_in', 'official_honorarium_time_out', 'official_servicecredit_time_in', 'official_servicecredit_time_out', 'official_overtime_time_in', 'official_overtime_time_out']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['day'].widget.attrs['readonly'] = True

# class CustomOfficialTimeFormSet(BaseModelFormSet):
#     def __init__(self, *args, **kwargs):
#         queryset = kwargs.pop('queryset', None)
#         super().__init__(*args, **kwargs)
#         for form in self.forms:
#             form.fields['employee_id'].widget.attrs['readonly'] = True
#             form.fields['day'].widget.attrs['readonly'] = True
#         self.queryset = queryset

#     model = OfficialTime
#     form = OfficialTimeForm
#     fields = '__all__'
#     extra = 0
#     min_num = 0
#     max_num = 0
#     renderer = get_default_renderer()
#     can_order = False  # Add this line to set can_order to False
# # class SearchForm(forms.Form):
# #     employee_id = forms.CharField(max_length=100)
# #     start_date = forms.DateField()
# #     end_date = forms.DateField()

class AttendanceRecordForm(forms.ModelForm):
    class Meta:
        model = AttendanceRecord
        fields = ['employee_id', 'date', 'time_in', 'break_in', 'break_out', 'time_out', 'surplusHour_time_in', 'surplusHour_time_out']

AttendanceRecordFormSet = modelformset_factory(AttendanceRecord, form=AttendanceRecordForm, extra=0)


class SearchForm(forms.Form):
    employee_id = forms.CharField(label='Employee ID', max_length=100)
    start_date = forms.DateField(label='Start Date', widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    end_date = forms.DateField(label='End Date', widget=forms.TextInput(attrs={'autocomplete': 'off'}))



class SearchAttendance(forms.Form):
    employee_id = forms.CharField(label='Employee ID', max_length=100)
    start_date = forms.DateField(label='Start Date', widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    end_date = forms.DateField(label='End Date', widget=forms.TextInput(attrs={'autocomplete': 'off'}))


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields =['username','email', 'password1', 'password2']
        
        
class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        exclude = ['user','employee_id']
        
        
class UploadFileForm(forms.Form):
    file = forms.FileField()

class FileUploadForm(forms.Form):
    file = forms.FileField()


class AttendanceSearchForm(forms.Form):
    employee_id = forms.CharField(max_length=100, required=False)
    start_date = forms.DateField(required=False)
    end_date = forms.DateField(required=False)

class AttendanceRecordForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AttendanceRecordForm, self).__init__(*args, **kwargs)
        # Disable employee_id and date fields
        self.fields['employee_id'].disabled = True
        self.fields['date'].disabled = True

    class Meta:
        model = AttendanceRecord
        fields = ['employee_id', 'date', 'time_in', 'break_in', 'break_out', 'time_out', 'surplusHour_time_in', 'surplusHour_time_out']

hris/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import *
from .forms import *
from django.contrib.auth import authenticate, login, logout
from .decorators import *
from .signals import *
from django.db.models import Q
#upload imports
import csv
import xlrd
import datetime
from datetime import datetime, timedelta
from django.urls import reverse  # Import reverse here
from django.conf import settings
import os
from django.forms import modelformset_factory
from django.forms import formset_factory
from django.http import HttpResponseRedirect
from django.http import HttpResponse
# Create your views here.

#UPLOAD DTR .DAT FILE
def upload_file(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = request.FILES['file']

            # Read and process each line in the uploaded file
            for line in uploaded_file:
                line = line.decode('utf-8').strip()  # Decode bytes to string and remove leading/trailing whitespace
                if line:  # Check if line is not empty
                    columns = line.split('\t')  # Split each line into columns based on tab delimiter

                    # Ensure that columns list has at least 2 elements before processing
                    if len(columns) >= 2:
                        employee_number = int(columns[0]) if columns[0].strip() else None

                        # Extract only the date part from columns[1]
                        date_time_parts = columns[1].split()
                        date_only = None
                        if len(date_time_parts) > 0:
                            date_only = date_time_parts[0]  # Extract only the date part
                            time_only = date_time_parts[1]
                        # Extracting other columns
                        if len(columns) >= 6:
                            column1 = int(columns[2])
                            column2 = int(columns[3])
                            column3 = int(columns[4])
                            column4 = int(columns[5])

                        # Check if an AttendanceRecord already exists for the employee and date
                        existing_records = AttendanceRecord.objects.filter(employee_id=employee_number, date=date_only)

                        # Create a new AttendanceRecord instance if it doesn't exist
                        if existing_records.exists():
                            record = existing_records.first()
                        else:
                            record = AttendanceRecord(employee_id=employee_number, date=date_only)
                        default_time = time(hour=0, minute=0, second=0)
                        # Assigning time components to the appropriate fields based on column values
                        # Note: I assume you want to save the full date_time string for time-related fields
                        if time_only:  # Check if date_time is not empty
                            if column1 == 1 and column2 == 0 and column3 == 1 and column4 == 0:      
                                    record.time_in = time_only
                            elif column1 == 1 and column2 == 1 and column3 == 1 and column4 == 0:
                                record.break_in = time_only
                            elif column1 == 1 and column2 == 4 and column3 == 1 and column4 == 0:
                                record.break_out = time_only
                            elif column1 == 1 and column2 == 5 and column3 == 1 and column4 == 0:
                                record.time_out = time_only
                            elif column1 == 1 and column2 == 4 and column3 == 0 and column4 == 0:
                                if  record.time_in != default_time:
                                    record.time_in = time_only
                                else:
                                    record.surplusHour_time_in = time_only    
                            elif column1 == 1 and column2 == 5 and column3 == 0 and column4 == 0:
                                if record.time_out != default_time:
                                    record.time_out = time_only
                                else:
                                    record.surplusHour_time_out = time_only

                        record.save()  # Save the record to the database

            return render(request, 'hris/upload_success.html')
    else:
        form = FileUploadForm()
    return render(request, 'hris/upload2.html', {'form': form})


def upload_success(request):
    return render(request, 'hris/upload_success.html')
#UPLOAD DTR END


@login_required(login_url='login')
@admin_only
def registerPage(request):
    if request.user.is_authenticated:

        form = CreateUserForm()
        groups = Group.objects.all()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                username = form.cleaned_data.get('username')

                group_name = request.POST.get('group')
                if group_name:
                    group = Group.objects.get(name=group_name)
                    user.save()
                    user.groups.add(group)

                employee_number = request.POST.get('employee_number')
                 # Create OfficialTime records for each day of the week
                days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
                for day in days_of_week:
                    OfficialTime.objects.create(
                            employee_id=employee_number,
                            day=day
                        )

                try:
                    # Try to retrieve existing employee profile for the user
                    employee_profile = Employee.objects.get(user=user)
                    # Update existing employee profile with new employee number and employment_status
                    employee_profile.employee_id = employee_number
                    employee_profile.employment_status = group_name
                    employee_profile.save()
                except Employee.DoesNotExist:
                        # Create new employee profile if it doesn't exist
                    employee_profile = Employee.objects.create(
                    user=user,
                    employee_id=employee_number,
                    first_name=user.first_name,
                    surname=user.last_name,
                    employment_status=group_name
                        )                

                   

                messages.success(request, 'Account was created for ' + username)
                return redirect('register')

        context = {'form': form, 'groups': groups}
        return render(request, 'hris/register.html', context)
       
    else:   
         return redirect('home')
    
@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'username and password is incorrect')

    context = {}
    return render(request, 'hris/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('login')


# @login_required(login_url='login')
@admin_only
def home(request):

    return render(request, 'hris/home.html',)

def pds1(request):
    employee = Employee.objects.get(user=request.user)

    # Render the employee data using a template
    return render(request, 'hris/pds1.html', {'employee': employee})

def pds2(request):
    employee = Employee.objects.get(user=request.user)

    # Render the employee data using a template
    return render(request, 'hris/pds2.html', {'employee': employee})

def pds3(request):
    employee = Employee.objects.get(user=request.user)

    # Render the employee data using a template
    return render(request, 'hris/pds3.html', {'employee': employee})

def pds4(request):
    employee = Employee.objects.get(user=request.user)

    # Render the employee data using a template
    return render(request, 'hris/pds4.html', {'employee': employee})


def accountSettings(request):
    employee = request.user.employee
    form = EmployeeForm(instance=employee)

    if request.method == 'POST':
        form = EmployeeForm(request.POST, request.FILES, instance=employee)
        if form.is_valid():
            # Save form data
            form.save()

            # Rename the profile picture if it exists
            if 'profile_pic' in request.FILES:
                # Get the uploaded profile picture
                profile_picture = request.FILES['profile_pic']

                # Rename the profile picture file using the username
                username = request.user.username
                file_name, file_extension = os.path.splitext(profile_picture.name)
                new_file_name = f"{username}{file_extension}"

                # Construct the correct file path
                file_path = os.path.join(settings.MEDIA_ROOT, new_file_name)

                # Rename the file in the filesystem
                with open(file_path, 'wb+') as destination:
                    for chunk in profile_picture.chunks():
                        destination.write(chunk)

                # Update the profile picture name in the customer object
                employee.profile_pic.name = new_file_name

hris/templates/hris/account_settings.html
{%  extends 'hris/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}



<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>
<div class="wrapper">
    {% include 'hris/navbar.html' %}     

    <div class="main p-3">
<div class="row">
	<div class="col-md-3 float-right">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'home' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.employee.profile_pic.url}}" >
			<hr>
			<a class="btn btn-warning" href="{% url 'pds1' %}">Personal Data Sheet</a>
		</div>
	</div>
	<div class="col-md-6 float-right">
		<div class="card card-body">
			
			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				{{form|crispy}}
		
			<input class="btn btn-primary" type="submit" name="Update Information">
			</form>
		</div>
	</div>
</div>
</div>
</div>

{% endblock %}

hris/templates/hris/edit_record.html
{%  extends 'hris/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}






    <p>{{ start_date|date:"Y-m-d" }}  {{ end_date|date:"Y-m-d" }}</p>
    <style>
        body {
            /* Gradient background */
            /* background: linear-gradient(to bottom, #fffec3, #750000); */
            /* Fallback color if gradients are not supported */
            background-color: maroon; /* Old browsers */
            /* Ensures the gradient stretches to fill the entire body */
            height: 100vh;
            margin: 0;
            /* You can add additional styles to the body here */
        }
    </style>
    <!-- <link rel="stylesheet" href="{% static './dist/css/jquery-ui-1.css' %}">
    <script src="{% static 'js/jquery-3.6.0-1.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui-1.js' %}"></script> -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 10vh; color: white;">
      <div class="register-logo">
        <a href="" style="color: #ffffff; text-decoration: none; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); font-size: 54px;"><b>EARIST</b> HRIS</a>
    
      </div>
    </div>
    
    <div class="form-group d-flex justify-content-center align-items-center" style="min-height: 20vh;" data-bs-theme="light">
    
        <div class="card" style="width: 30rem;">
            <div class="card-body">
     
                <a href="" style="color: maroon; text-decoration: none; text-shadow: 2px 2px 4px rgba(255, 255, 255, 0.5); font-size: 30px; display: block; margin: 0 auto; width: fit-content; text-align: center;"><b>Edit Attendance Record</b></a><br>
          
   <form method="post">
       {% csrf_token %}
       {{ form | crispy }}
       <input type="hidden" name="start_date" value="{{ start_date |date:'Y-m-d' }}">
       <input type="hidden" name="end_date" value="{{ end_date |date:'Y-m-d' }}">
       <button class="btn btn-primary btn-lg btn-block" type="submit"><b>Save</b></button>
   </form>

</div>
</div>

   {% endblock content %}

hris/templates/hris/footer.html
<div class="container-fluid">
    <footer class="footer d-flex justify-content-center align-items-center">
      <p>&copy; 2024 EARIST</p>
    </footer>
  </div>

hris/templates/hris/search_attendance_record.html
{%  extends 'hris/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="wrapper">
        {% include 'hris/navbar.html' %}      
        <div class="main p-3">
            <div class="text-center">
                <div class="row">
                    <style>
                        body {
                            /* Gradient background */
                            /* background: linear-gradient(to bottom, #fffec3, #750000); */
                            /* Fallback color if gradients are not supported */
                            background-color: maroon; /* Old browsers */
                            /* Ensures the gradient stretches to fill the entire body */
                            height: 100vh;
                            margin: 0;
                            /* You can add additional styles to the body here */
                        }
                    </style>
                    <!-- <link rel="stylesheet" href="{% static './dist/css/jquery-ui-1.css' %}">
                    <script src="{% static 'js/jquery-3.6.0-1.min.js' %}"></script>
                    <script src="{% static 'js/jquery-ui-1.js' %}"></script> -->
                    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
                    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
                    
                    <div class="container d-flex justify-content-center align-items-center" style="min-height: 20vh; color: white;">
                      <div class="register-logo">
                        <a href="{% url 'home' %}" style="color: maroon; text-decoration: none; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); font-size: 54px;"><b>EARIST</b> HRIS</a>
                    
                      </div>
                    </div>
                    
                    <div class="form-group d-flex justify-content-center align-items-center" style="min-height: 20vh;" data-bs-theme="light">
                    
                        <div class="card" style="width: 30rem;">
                            <div class="card-body">
                     
                                <a href="" style="color: maroon; text-decoration: none; text-shadow: 2px 2px 4px rgba(255, 255, 255, 0.5); font-size: 30px; display: block; margin: 0 auto; width: fit-content; text-align: center;"><b>Update Attendance Record</b></a><br>
                                
                              <form class="" method="post" data-bs-theme="primary">
                                  {% csrf_token %}
                                  {{ form | crispy }}
                                  <button class="btn btn-primary btn-lg btn-block" type="submit"><b>Search</b></button>
                              </form>
                            </div>
                          </div>
                    
                         
                    
                    
                    
                    </div>
                    
                        <script>
                            $(document).ready(function() {
                                $("#id_start_date").datepicker({
                                    dateFormat: 'yy-mm-dd',
                                    changeMonth: true,
                                    changeYear: true,
                                    // Add any additional options you want here
                                });
                                
                                $("#id_end_date").datepicker({
                                    dateFormat: 'yy-mm-dd',
                                    changeMonth: true,
                                    changeYear: true,
                                    // Add any additional options you want here
                                });
                            });
                        </script>   
                </div>
                
            </div>
            {% include 'hris/footer.html' %}  
          </div>
          
        </div>
    </div>
    {% endblock content %}

hris/templates/hris/search_records.html
{%  extends 'hris/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="wrapper">
        {% include 'hris/navbar.html' %}      
        <div class="main p-3">
            <div class="text-center">
                <div class="row">
                    <style>
                        body {
                            /* Gradient background */
                            /* background: linear-gradient(to bottom, #fffec3, #750000); */
                            /* Fallback color if gradients are not supported */
                            background-color: maroon; /* Old browsers */
                            /* Ensures the gradient stretches to fill the entire body */
                            height: 100vh;
                            margin: 0;
                            /* You can add additional styles to the body here */
                        }
                    </style>
                    <!-- <link rel="stylesheet" href="{% static './dist/css/jquery-ui-1.css' %}">
                    <script src="{% static 'js/jquery-3.6.0-1.min.js' %}"></script>
                    <script src="{% static 'js/jquery-ui-1.js' %}"></script> -->
                    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
                    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
                    
                    <div class="container d-flex justify-content-center align-items-center" style="min-height: 20vh; color: white;">
                      <div class="register-logo">
                        <a href="" style="color: #ffffff; text-decoration: none; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); font-size: 54px;"><b>EARIST</b> HRIS</a>
                    
                      </div>
                    </div>
                    
                    <div class="form-group d-flex justify-content-center align-items-center" style="min-height: 20vh;" data-bs-theme="light">
                    
                        <div class="card" style="width: 30rem;">
                            <div class="card-body">
                     
                                <a href="" style="color: maroon; text-decoration: none; text-shadow: 2px 2px 4px rgba(255, 255, 255, 0.5); font-size: 30px; display: block; margin: 0 auto; width: fit-content; text-align: center;">Generate DTR</a><br>
                              <form class="" method="post" data-bs-theme="primary">
                                  {% csrf_token %}
                                  {{ form | crispy }}
                                  <button class="btn btn-primary btn-lg btn-block" type="submit">Search</button>
                              </form>
                            </div>
                          </div>
                    
                         
                    
                    
                    
                    </div>
                    
                        <script>
                            $(document).ready(function() {
                                $("#id_start_date").datepicker({
                                    dateFormat: 'yy-mm-dd',
                                    changeMonth: true,
                                    changeYear: true,
                                    // Add any additional options you want here
                                });
                                
                                $("#id_end_date").datepicker({
                                    dateFormat: 'yy-mm-dd',
                                    changeMonth: true,
                                    changeYear: true,
                                    // Add any additional options you want here
                                });
                            });
                        </script>   
                    
                </div>
                
            </div>
            {% include 'hris/footer.html' %}  
          </div>
          
        </div>
    </div>
    {% endblock content %}

hris/templates/hris/upload2.html
{%  extends 'hris/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="wrapper">
        {% include 'hris/navbar.html' %}      
        <div class="main p-3">
            <div class="text-center">
                <div class="row">
                    


<style>
    body {
        /* Gradient background */
        /* background: linear-gradient(to bottom, #fffec3, #750000); */
        /* Fallback color if gradients are not supported */
        background-color: maroon; /* Old browsers */
        /* Ensures the gradient stretches to fill the entire body */
        height: 100vh;
        margin: 0;
        /* You can add additional styles to the body here */
    }
</style>
<!-- <link rel="stylesheet" href="{% static './dist/css/jquery-ui-1.css' %}">
<script src="{% static 'js/jquery-3.6.0-1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.js' %}"></script> -->
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<div class="container d-flex justify-content-center align-items-center" style="min-height: 20vh; color: white;">
  <div class="register-logo">
    <a href="" style="color: maroon; text-decoration: none; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); font-size: 54px;"><b>EARIST</b> HRIS</a>

  </div>
</div>

<div class="form-group d-flex justify-content-center align-items-center" style="min-height: 20vh;" data-bs-theme="light">

    <div class="card" style="width: 30rem;">
        <div class="card-body">
 
            <a href="" style="color: maroon; text-decoration: none; text-shadow: 2px 2px 4px rgba(255, 255, 255, 0.5); font-size: 30px; display: block; margin: 0 auto; width: fit-content; text-align: center;"><b>UPLOAD ATTENDANCE LOG</b></a><br>

          <form class="" method="post" data-bs-theme="primary">
              {% csrf_token %}
              {{ form | crispy }}
              <button class="btn btn-primary btn-lg btn-block" type="submit">Search</button>
          </form>
        </div>
      </div>

     



</div>

    <script>
        $(document).ready(function() {
            $("#id_start_date").datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true,
                // Add any additional options you want here
            });
            
            $("#id_end_date").datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true,
                // Add any additional options you want here
            });
        });
    </script>   

                </div>
                
            </div>
            {% include 'hris/footer.html' %}  
          </div>
          
        </div>
    </div>
    {% endblock content %}